streams:
  - name: test-event-stream                                                          # Unique name for this domain event stream
    kafka_topic: e2e-crmandmarketing-marketingandcrmanalytics-test-event-stream-v1   # Kafka topic to publish/consume
    entity_version: v1
    level_0: crmandmarketing
    level_1: martketingchannelmanagement
    kafka_topic_entity_name: test-event-stream
    max_tasks: 3
    schemas_enable: true
    materialize: true
    iedm_schema: crmandmarketing/mailchimp/marketingandcrmanalytics/entities/Attribution.schema.json

    labels:                                                                          # optional labels for cost attribution and team mapping
      intuit-billing-capability: mc-data-understanding
      intuit-billing-service: data-quality