streams:
- name: predicteddemographics
  kafka_topic: prd.aifabric.crmandmarketing.mailchimp.predicteddemographics.v1
  kafka_topic_entity_name: predicteddemographics
  entity_version: v1
  level_0: aifabric
  level_1: crmandmarketing
  max_tasks: 64
  schemas_enable: true
  publishers:
    - serviceAccount:rsg-audience-prod-sa@rsg-audience-expansion-prod.iam.gserviceaccount.com
- name: mtlc2metrics
  kafka_topic: prd-aifabric-crmandmarketing-mailchimp-mtlc2metrics-v3
  kafka_topic_entity_name: mtlc2metrics
  entity_version: v3
  level_0: crmandmarketing
  level_1: mailchimp
  max_tasks: 12
  schemas_enable: true
  publishers:
    - serviceAccount:82418792444-compute@developer.gserviceaccount.com
- name: mtlc2metrics_activation
  kafka_topic: prd-aifabric-crmandmarketing-mailchimp-mtlc2metrics-v1-activation
  kafka_topic_entity_name: mtlc2metrics_activation
  entity_version: v1
  level_0: crmandmarketing
  level_1: mailchimp
  max_tasks: 3
  schemas_enable: true
  publishers:
    - serviceAccount:82418792444-compute@developer.gserviceaccount.com
